version: '3.8'

services:
  web:
    build:
      context: ./app
      # dockerfile: Dockerfile
    ports:
      - 80:80
    command: uvicorn main:app --host 0.0.0.0 --reload --port 80

    # volumes:
    #   - ./app:/usr/src/app
